parallel-jobs = 1
logging-to-file = false        # enables logging of every patch process to a seperate file
enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "apk"                                                 # 'both', 'apk' or 'module'
excluded-patches = ""                                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = ""                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "auto"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music-Extended]
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "both"

[YouTube-Extended]
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music]
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "both"

[Twitter]
build-mode = "apk"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[Twitch]
uptodown-dlurl = "https://twitch.en.uptodown.com/android"

[TikTok]
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"

[Reddit]
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Lightroom]
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
apkmirror-arch = "arm64-v8a + x86_64"

[Messenger]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "arm64-v8a"

[Spotify]
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Citra]
apkmirror-dlurl = "https://www.apkmirror.com/apk/citra-emulator/citra-emulator/"
apkmirror-arch = "arm64-v8a"

[Backdrops]
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"

[WarnWetter]
apkmirror-dlurl = "https://www.apkmirror.com/apk/deutscher-wetterdienst/warnwetter/"

[Windyapp]
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[IconPackStudio]
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[Spotify-Lite]
uptodown-dlurl = "https://spotify-lite.en.uptodown.com/android/"

[com.zombodroid.MemeGenerator]
apkmirror-dlurl = "https://www.apkmirror.com/apk/zombodroid/meme-generator-free/"

[Instagram-arm64]
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
apkmirror-arch = "arm64-v8a"

[Instagram-arm]
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
apkmirror-arch = "arm-v7a"

[Facebook-Messenger-arm64]
version = "auto"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android/"
arch = "arm64-v8a"

[Facebook-Messenger-arm]
version = "auto"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android/"
arch = "arm-v7a"

[VSCO-CAM]
apkmirror-dlurl = "https://www.apkmirror.com/apk/vsco/vsco-cam/"

[CandyVPN]
apkmirror-dlurl = "https://www.apkmirror.com/apk/liondev-io/candylink-vpn/"

[DuoLingo]
uptodown-dlurl = "https://duolingo.en.uptodown.com/android/"

[Nova-Launcher]   
apkmirror-dlurl = "https://www.apkmirror.com/apk/teslacoil-software/nova-launcher/"

